### ISSUE TITLE
Front End development

### ISSUE THREAD

**Issue by andrewnijmeh** [discordutilitybot/utilitybot#4]
This is some front end work to be done for the domain/website utilitybot.co here is an idea of what it will be like and the redirects
we will have a page about commands on how to use it what it does and the bot prefix. redirects:
utilitybot.co/commands (list of commands based on categories)
utilitybot.co/invite (redirects you to inviting the bot with the discord bot invite link ill give you the link once you need it ;D)
utilitybot.co/bot (explains the bot what it does etc) i may add more redirects if we really need more.
utilitybot.co/contact (just some basic contact info like the invite to the discord and the email) (ill create the email when we actually need an email for contacts
utilitybot.co/features (just a tab to explain what it can do) (this isn't like the commands page it will really just explain what the bot can do..)
utilitybot.co/privacy (telling users what data we collect etc)

Also i sorta want the theme to look like rythm bots website https://rythmbot.co/ 

sorry if this was alot to take in but i really appreciate this front end work ;D

**Comment by PineappleRind** [comment]
what about putting utilitybot.co/features and utilitybot.co/bot both on the homepage?

**Comment by andrewn6** [comment]
Yeah that sounds good the user can scrol, down the check three features but the commands area separate page/reidrect

**Comment by andrewn6** [comment]
Ill start adding the HTML files in the HTML folder also there will be nothing in the folder so don't worry about committing the code then overwriting  the file since there is really nothing in the files by the way we can also add a /faq redirect for information on the bot like the number of servers what commands a user can use what commands a mod can use and overall just info about the whole bot (a dropdown for it would be nice kinda like what rythmbot.co/faq did)

**Comment by PineappleRind** [comment]
I have a [website project board](https://github.com/users/PineappleRind/projects/1) open-

**Comment by ghost** [comment]
Sorry for replying this late; this looks good to me. 

Once I'm finished the design, I will work with @PineappleRind to finish the site.

**Comment by andrewn6** [comment]
Yep sounds good
